version: '3'
services:
  db-postgres-dest:
    image: 'debezium/postgres:9.6'
    hostname: postgres-dest
    ports:
      - "15432:5432"
    environment:
      TZ: Australia/Sydney
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydestination
    extra_hosts:
      - "moby:127.0.0.1"

  db-postgres-audit:
    image: 'debezium/postgres:9.6'
    hostname: postgres-audit
    ports:
      - "5432:5432"
    environment:
      TZ: Australia/Sydney
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myaudit
    extra_hosts:
      - "moby:127.0.0.1"

  db-oracle-source:
    image: 'alexeiled/docker-oracle-xe-11g'
    hostname: oracle-source
    ports:
      - "1521:1521"
    environment:
      TZ: Australia/Sydney
    volumes:
      - ./demonstration:/tmp/custom
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper:
    image: 'confluentinc/cp-zookeeper'
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      TZ: Australia/Sydney
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  broker:
    image: 'confluentinc/cp-enterprise-kafka'
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      TZ: Australia/Sydney
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    extra_hosts:
      - "moby:127.0.0.1"

  schema_registry:
    image: 'confluentinc/cp-schema-registry'
    hostname: schema_registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      TZ: Australia/Sydney
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'
    extra_hosts:
      - "moby:127.0.0.1"
      
  schema_registry_ui:
    image: 'landoop/schema-registry-ui'
    hostname: schema_registry_ui
    depends_on:
      - schema_registry
    ports:
      - "8002:8000"
    environment:
      TZ: Australia/Sydney
      KAFKA_REST_PROXY_URL: "http://kafka_rest:8082"
      SCHEMAREGISTRY_URL: 'http://schema_registry:8081'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      PROXY: "true"
      PROXY_SKIP_VERIFY: "true"
      MAX_BYTES: "20000000"
    extra_hosts:
      - "moby:127.0.0.1"

  kafka_rest:
    image: 'confluentinc/cp-kafka-rest'
    hostname: kafka_rest
    depends_on:
      - broker
      - zookeeper
      - schema_registry
    ports:
      - "8082:8082"
    environment:
      TZ: Australia/Sydney
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082'
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:9092'
      KAFKA_REST_HOST_NAME: 'kafka_rest'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
    extra_hosts:
      - "moby:127.0.0.1"

  kafka_topics_ui:
    image: 'landoop/kafka-topics-ui'
    hostname: kafka_topics_ui
    depends_on:
      - kafka_rest
    ports:
      - "8000:8000"
    environment:
      TZ: Australia/Sydney
      KAFKA_REST_PROXY_URL: "http://kafka_rest:8082"
      PROXY: "true"
      PROXY_SKIP_VERIFY: "true"
      MAX_BYTES: "20000000"
    extra_hosts:
      - "moby:127.0.0.1"      
      
  data-pipeline:
    image: 'iag/datapipeline:latest'
    build:
      context: docker/
    hostname: data-pipeline
    depends_on:
      - db-postgres-dest
      - db-postgres-audit
      - db-oracle-source
      - zookeeper
      - broker
      - schema_registry
    ports:
      - "5000:5000"
    environment:
      TZ: Australia/Sydney
      LD_LIBRARY_PATH: '/usr/lib/oracle/12.2/client64/lib'
#      HTTPS_PROXY: ''
#      https_proxy: ''
    volumes:
      - .:/usr/local/data_pipeline
    extra_hosts:
      - "moby:127.0.0.1"
