#!/bin/bash

# This script should be run within Oracle container
export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
export ORACLE_SID=XE
export PATH=${PATH}:${ORACLE_HOME}/bin

cd /tmp/custom/
sqlplus  @ /tmp/custom/setup_oracle_db.sql
exit
