#!/bin/sh

# This script should be run on the docker host

# Start
# The first time you do this it will take a long time as a lot of public Docker files are being downloaded
docker-compose up -d

sleep 20

# Log into db-oracle-source and setup arch logging, supplemntal logging and tables
docker-compose exec --user=oracle db-oracle-source /tmp/custom/setup_oracle

# Log into data-pipeline machine and setup postgres db
docker-compose exec data-pipeline /usr/local/data_pipeline/demonstration/setup_postgres

# Log into data-pipeline machine and compile pipeline code
docker-compose exec data-pipeline /usr/local/data_pipeline/demonstration/setup_pipeline
